---
title: "Resume of Qin Huang"
---

## Contact

-   Name: Qin Huang
-   Mobile: (734)-263-7828
-   Email: [qh2284\@cumc.columbia.edu](mailto:qh2284@cumc.columbia.edu){.email}
-   Address: 60 Haven Avenue, New York, NY 10032

------------------------------------------------------------------------

## EDUCATION

**Columbia University, Mailman School of Public Health** <span style="float: right; font-weight: bold;">New York, NY</span>

MS in Biostatistics - *GPA: 4.21/4* <div style="text-align: right; float: right;">expected May, 2025</div>

-   Coursework: Survival analysis, Analysis of Longitudinal Data, Data science I & II

**University Of Michigan** <span style="float: right; font-weight: bold;">Ann Arbor, MI</span>

BSE in Biomedical Engineering   - *GPA: 4.0/4* <div style="text-align: right; float: right;">Apr, 2023</div>

- Coursework: Introduction to Database, Introduction to R computing, Python Visualization
- Award: James B. Angell Scholar

**Shanghai Jiao Tong University** <span style="float: right; font-weight: bold;">Shanghai, China</span>

BSE in Electrical and Computer Engineering   - *GPA: 3.53/4* <div style="text-align: right; float: right;">Aug, 2023</div>

- Coursework: Probabilistic Methods in Eng., Intro to Signals and Systems, Intro to Circuits, Matlab programming
- Award: SJTU Undergraduate Excellent Scholarship

------------

## SKILL
- Programming: R / R shiny, SQL, SAS (Base & Advance certificate), MATLAB, Python, LaTeX, C
- Software: Excel, PowerPoint

-------------

## WORK EXPERIENCE
**Daiichi Sankyo Inc. (Intern)** <span style="float: right; font-weight: bold;">Basking Bridge, NJ</span>

Statistical programmer <div style="text-align: right; float: right;">Jun, 2024 - Aug, 2024</div>

- Applied SAS to create tables, figures, and listings (TFLs) including summary of population, summary of demographic and baseline characteristics, shifts of laboratory values and curve for time to dermatologic event.
- Developed an app to enhance flexibility and efficiency in designing clinical trials for innovative cancer therapies, significantly reducing costs for the company. The app supports various survival distributions, such as piecewise exponential and mixture cure rate models, with options for proportional hazards. It allows customization of enrollment curves and provides flexible statistical testing options at each analysis point, including logrank tests and customized weighted logrank tests, to better model complex survival curves and improve trial outcomes.

**Astrazeneca (Intern)** <span style="float: right; font-weight: bold;">Shanghai, China</span>

Oncology programmer <div style="text-align: right; float: right;">May, 2023 - Jul, 2023</div>

- Designed and implemented an algorithm on profile likelihood confidence interval calculation based on R programming with less than 1% difference compared to SAS results where working with harzard ratio and cox model

-------------

## PROJECT AND COMPETITION
**Columbia University** <span style="float: right; font-weight: bold;">New York, NY</span>

<i>Autism Project </i> <span style="float: right;">Mar, 2024 - present</span>

- The project focuses on classification among different groups, including autism, developmental disabilities and typically developing. Random forest contributes to selecting 30 most important factors and reducing the low-value information. LASSO is conducted to calculate the coefficients and shrink the unimportant factors to zero which benefit the com- plexity and interpretability of the model.
- Results: The final results interpret how each parameters affect the distinguish among groups and how much they contribute, providing innovative guidance to further focus on specific aspects for future research.

<i>Logistic regression for factors contributing to depression </i> <span style="float: right;">Nov, 2023 - Dec, 2023</span>

- Collect data from DASS-42 responses and conduct data cleaning. Develop a shiny app for visualization and conduct exploratory data analysis. Apply chi-squared tests and apply logistic regression on the relationship between depression level and factors.
- Results: The depression level is associated with country, age, gender, race and orientation.

**University Of Michigan** <span style="float: right; font-weight: bold;">Ann Arbor, MI</span>

<i>Statistics-based XAI approach for neural network decision analysis</i> <span style="float: right;">Jul, 2023 - Dec.2023</span>

- Introduce a pedagogical approach applying PCA and MLR to simulate and interpret the inner structure of Neuron Networks working on 2D image.

- **Results:** Successfully establish a neural network interpretation framework for hand-written digit recognition. Methods proven with higher accuracy, robustness, and sensitivity to global and local texture information compared with the existing method.

<i>Experimenting escaping behavior of larvae under repetitive weak stimulation</i> <span style="float: right;">May, 2022 - May, 2023</span>

- Collected virgins, planned on hybridization, prepared ATR food and designed genotypes of both a control group and an experimental group; Conducted escaping behavioral experiments working on hundreds of data. Took care of larvae stocks, and autoclaved the pipettes;

- **Results:** There is no sufficient evidence to draw on the correlation between escaping behavior and repetitive weak stimulation for a specific range of spectrum. However, different light compositions could still play a role in shaping the escaping behavior of larvae.

<i>Mask R-CNN for rat behavior identification</i> <span style="float: right;">May, 2022 - Nov, 2022</span>

- Wrote codes for the entire program and processed each frameimage of the video with Python (using VIA to mark an object within a frame and then generate a JSON file), created train and validation groups, conducted training by using the pre-trained COCO dataset with Mask R-CNN

- **Results:** The shape of the mouse could be masked in the motion video, with an accuracy over 0.7 which potentially leads to new approach of Detectron2.




